obstacle_range: 3.5
raytrace_range: 4.0
footprint: [[-0.02, -0.02], [-0.02, 0.02], [0.02, 0.02], [0.02, -0.02]]
inflation_radius: 1.7
transform_tolerance: 0.3

observation_sources: scan
scan:
  data_type: LaserScan
  topic: /laser/scan
  marking: true
  clearing: true

map_type: costmap

