local_costmap:
  global_frame: odom
  robot_base_frame: base_link 
  update_frequency: 5.0 #before 5.0
  publish_frequency: 2.0 #before 2.0
  static_map: false
  rolling_window: true
  width: 2.0
  height: 2.0
  resolution: 0.025 #increase to for higher res 0.025
  transform_tolerance: 0.5
  cost_scaling_factor: 5.0
  inflation_radius: 1.5

