TrajectoryPlannerROS:
  max_vel_x: 1.3
  min_vel_x: -0.5
  max_vel_theta: 2.2
  min_vel_theta: -2.2
  min_in_place_vel_theta: 2.2
  acc_lim_theta: 2.2
  acc_lim_x: 2.0
  acc_lim_y: 0.5
  holonomic_robot: false

# Forward Simulation Parameters
  sim_time: 1.5
  vx_samples: 20
  vy_samples: 0
  vth_samples: 40
  controller_frequency: 5.0

# Trajectory Scoring Parameters
  path_distance_bias: 53.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true
